- name: Upload to IPFS
  # You may pin to the exact commit or the version.
  # uses: aquiladev/ipfs-action@69c811bf0c5ad0dd14427bd043343119b9d1f7e0
  uses: aquiladev/ipfs-action@v0.1.6
  with:
    # Directory path to upload
    path: releases/download/v1.0/100MB.bin
    # Type of target service to upload. Supported services [ipfs, pinata, infura]
    service: # optional, default is ipfs
    # Request timeout
    timeout: # optional, default is 60000
    # Level of verbosity
    verbose: # optional
    # [ipfs] IPFS host
    host: # optional, default is ipfs.komputing.org
    # [ipfs] IPFS port
    port: # optional, default is 443
    # [ipfs] IPFS protocol
    protocol: # optional, default is https
    # [ipfs] IPFS headers as json object
    headers: # optional, default is {}
    # [pinata] Api Key. Required for pinata service
    pinataKey: # optional
    # [pinata] Secret Api Key. Required for pinata service
    pinataSecret: # optional
    # [pinata] Human name for pin
    pinataPinName: # optional
