# This is a basic workflow to help you get started with Actions

name: CI
env:
  user: "hybla"
  name: "noob"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a script
        run: |
          wget http://ping.online.net/50Mo.dat
          ls -l
          pwd
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: testfile
          # A file, directory or wildcard pattern that describes what to upload
          path: 50Mo.dat
          # The desired behavior if no files are found using the provided path.
      
      - name: environment settings
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: IPFS Setup Action
        # You may pin to the exact commit or the version.
        # uses: ibnesayeed/setup-ipfs@e183d0d2538b866dc30d8850883bd4cd4f8ab431
        uses: ibnesayeed/setup-ipfs@0.6.0
        with:
          # Whether to start IPFS service daemon after installation and initialization
          run_daemon: true
      
      - name: Test IPFS
        shell: bash
        run: |
          ipfs cat /ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m
          cid=$(ipfs add -Q 50Mo.dat)
          echo $cid
          ipfs pin add $cid
